info:
  # Blog Information
  title:        "Learning With Errors"
  subtitle:     "a theory student blog"
  cover_image:  mountains_banff.JPG
  cover_image_caption: ""
  logo:         logo.png
  description: "a theory student blog"

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  learningwitherrors

  # Google Analytics tracking ID. Leave blank to disable tracking
  google-analytics-id: UA-78524899-1

# Root URL where the site will be published
url:         http://learningwitherrors.org

paginate:             10

header_links:
    - url: "/"
      title: "Blog"
    - url: "/about/"
      title: "About"
    - url: "/contributing/"
      title: "Contributing"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      permalink: /:year/:month/:day/:title.html
      #excerpt: ""
      excerpt_separator: <!--more-->

sass:
    sass_dir: _sass

markdown: kramdown
kramdown:
    math_engine: nil # this doesn't actually disable it... so instead,
        # there is a javascript hack in _includes/footer_script.html that replaces
        # all the script type math/tex tags with $$...$$, as it was before
        # kramdown messed it up.


