info:
  # Blog Information
  title:        "Learning With Errors"
  subtitle:     "theory student blog"
  cover_image:  mountains_banff.JPG
  cover_image_caption: ""
  logo:         logo.png
  #description: ""

  # Social links
  # facebook:
  #twitter:
  #github:
  # gplus:

  # Comments
  disqus:
    # Eg. "exampleblog" Set to false to disable comments
    shortname:  learningwitherrors

  # Google Analytics tracking ID. Leave blank to disable tracking
  google-analytics-id:

  # Sharing settings
  sharing:
    twitter:    false
    facebook:   false
    gplus:      false
    hn:         false
    reddit:     false

  # Google Fonts
  # eg. 'Droid+Sans:400,700|Droid+Serif:400,700'
  # google_font: 'Droid+Sans:400,700'


# Root URL where the site will be published
url:         http://learningwitherrors.org

paginate:             10

header_links:
    - url: "/"
      title: "Blog"
    - url: "/about/"
      title: "About"
    - url: "/contributing/"
      title: "Contributing"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      permalink: /:year/:month/:day/:title.html
      excerpt: ""
      #excerpt_separator: <!--more--> # doesn't work.... ??? TODO.

sass:
    sass_dir: _sass
